name: Update Winners

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Winner Tracker
        run: node tracker.mjs
        env:
          HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}

          - name: Commit changes
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"
    git add winners.json
    git commit -m "Update winners"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



